### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by DjebbZ** [developit/proptypes#1]
Hi,

I love the idea of using the concept of PropTypes to validate any data in any js code. I briefly skimmed the code but didn't find an exposed function like `check(dataToValidate, propTypes)`. Did I miss something ?

**Comment by developit** [comment]
@DjebbZ: I will add a usage example, but it's the same as React.PropTypes. they are validator functions called in series. Will post here once it's in the README. Thanks!

**Comment by developit** [comment]
``` js
function check(props, propTypes) {
    for (let prop in propTypes) {
        if (propTypes.hasOwnProperty(prop)) {
            let err = propTypes[prop](props, prop, 'name', 'prop');
            if (err) {
                console.warn(err);
                return false;
            }
        }
    }
    return true;
}
```

**Comment by yavuzmester** [comment]
it would be much better if you expose the check function. Or I or many others may need to create our own npm modules by copying the above check function. Thanks.

**Comment by developit** [comment]
I'd recommend creating a new module for that to keep things nice and separate 👍
This module is just a copy and paste of the original, so I don't want to modify it too much.
